title: "http_status_code_road_signs"
description: "HTTP Status Code Images from Japanese Road Signs."
baseurl: "/http_status_code_road_signs"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge
markdown: "GFM"